/**
 * 
 */
package com.jyt.terminal.commom.enums;

/**
 * 
 * @author 
 */
public enum TradeRetCodeEnum implements ServiceExceptionEnum{
	TRADE_SUCCESS (1000,"交易成功"),
	TRADE_ERRRO_1001(1001, "系统出错-001"), // 系统一般异常
	TRADE_ERROR_1002(1002, "系统出错-002"), // 无渠道实现类
	TRADE_ERROR_1003(1003, "系统出错-003"), // 证书加载失败
	TRADE_ERROR_1004(1004, "系统出错-004"), // 签名出错
	TRADE_ERROR_1005(1005, "系统出错-005"), // 渠道返回信息解析出错
	TRADE_ERROR_1006(1006, "系统出错-006"), // 无可用渠道
	TRADE_ERROR_1007(1007, "系统出错-007"), // 连接渠道出错
	TRADE_ERROR_1008(1008, "系统出错-008"), // 写文件出错
	TRADE_ERROR_1009(1009, "系统出错-009"), // 渠道返回信息有误
	TRADE_ERROR_1010(1010, "系统出错-010"), // 文件Base64编码出错
	TRADE_ERROR_1012(1012, "系统出错-1012"), // 尚未未申请协议号
	TRADE_ERROR_1013(1013, "系统出错-1013"), // 使用公钥加密字段失败
	TRADE_ERROR_1014(1014, "协议已存在"), 
	TRADE_ERROR_1015(1015, "协议已生效"), 
	TRADE_ERROR_1016(1016, "申请记录不存在"), 
	TRADE_ERROR_1017(1017, "原申请无效，请重新申请"), 

	TRADE_ERROR_1101(1101, "系统出错-1101"), // 渠道交易失败
	TRADE_ERROR_1102(1102, "系统出错-1102"), // 验证渠道签名出错
	
	TRADE_ERROR_PARAM_NULL_ERROR(1101,"请求参数不能为空"),
	TRADE_ERROR_ORDER_NO_EXISTS(1102, "订单号重复"), 
	TRADE_ERROR_ORDER_NO_NOT_EXIST_ERROR(1103,"订单信息不存在"),
	TRADE_ERROR_SMS_SEND_ERROR(1104,"验证码发送失败"),
	TRADE_ERROR_SMS_VERIFY_ERROR(1105,"验证码验证失败"),
	TRADE_ERROR_SMS_SEND_QUICKLY_ERROR(1106,"验证码发送频率过快"),
	TRADE_ERROR_CERTIFICATE_NO_NOT_SUPPORT(1107,"证件号码只支持18或15位身份证"),
	TRADE_ERROR_EXPIRY_DATE_UNENOUGH_ERROR(1108,"证件有效期期限不足"),
	TRADE_ERROR_FILE_MD5_CHECK_EXCEPTION(1109,"md5校验异常"),
	TRADE_ERROR_FILE_MD5_CHECK_ERROR(1110,"md5文件签名校验不通过"),
	TRADE_ERROR_BATCH_MAX_COUNT_ERROR(1111,"超过批量最大笔数{}笔限制"),
	TRADE_ERROR_STRING_REPLACE_ERROR(1112,"字符串替换错误"),
	TRADE_ERROR_REQUEST_DATE_ERROR(1113,"请求参数转换错误"),
	TRADE_ERROR_REQUEST_STARTINDEX_ERROR(1114,"起始行必须大于等于1"),
	TRADE_ERROR_REQUEST_STARTINDEX_EMPTY_ERROR(1115,"起始行不能为空"),
	TRADE_ERROR_REQUEST_ENDINDEX_ERROR(1116,"结束行必须不小于1"),
	TRADE_ERROR_REQUEST_ENDINDEX_EMPTY_ERROR(1116,"结束行不能为空"),
	TRADE_ERROR_REQUEST_ENDINDEX_LT_STARTINDEX_ERROR(1116,"结束行不能小于起始行"),
	TRADE_ERROR_REQUEST_ENDINDEX_GT_STARTINDEX_100_ERROR(1117,"结束行减去起始行不能大于100"),
	TRADE_ERROR_REQUEST_CHANNEL_ID_ERROR(1118,"渠道ID不匹配"),
	TRADE_ERROR_REQUEST_SENSITIVE_INFO_ENCRYPT_PROCESS_ERROR(1119,"敏感信息加密/解密异常"),
	TRADE_ERROR_FILE_NOT_EXIST_EXCEPTION(1120,"找不到对应的文件"),
	TRADE_ERROR_TREATY_STATUS_ERROR(1121,"申请失效，请重新申请"),
	TRADE_ERROR_TREQUEST_PARAM_ILLEGAL(1122,"参数错误"),
	TRADE_ERROR_ENCRYPT_ERROR(1123,"加密错误"),
	TRADE_ERROR_DECRYPT_ERROR(1124,"解密错误"),
	TRADE_ERROR_INVALIDE_CERT_TYPE(1125,"该证件类型不支持"),
	
	E_SIGN_ERROR_MEDIA_DIGEST_ERROR(2003,"合同文件签名不匹配"),
	E_SIGN_ERROR_MEDIA_FORMAT_ERROR(2004,"合同文件格式不正确"),
	E_SIGN_ERROR_MEDIA_CONTENT_ERROR(2005,"合同文件内容不正确"),
	E_SIGN_ERROR_MEDIA_NOT_FOUND_ERROR(2006,"合同文件未找到"),
	E_SIGN_ERROR_SIGN_INFOS_ERROR(2008,"签约人信息为空"),
	E_SIGN_ERROR_INVESTMENT_INFO_ERROR(2009,"文本域信息格式不正确，转换异常"),
	E_SIGN_ERROR_CONTRACT_INFO_NULL_ERROR(2010,"合同信息为空"),
	E_SIGN_ERROR_BATCH_SIGN_INFOS_ERROR(2011,"以下订单 {}，签约人信息为空"),
	E_SIGN_ERROR_FILE_NOT_EXISTS_ERROR(2014,"未上传待签署合同"),
	E_SIGN_ERROR_FILE_CHECK_DIGEST_ERROR(2015,"文件签名不匹配"),
	E_SIGN_ERROR_PLATFORM_SIGNLOCATION_ERROR(2016,"平台签名域信息为空"),
	E_SIGN_ERROR_INVESTMENT_INFO_EMPTY_ERROR(2027,"文本域信息信息不能为空"),
	E_SIGN_ERROR_ENDDATE_LGE_SYSDATE_ERROR(2028,"协议失效日期不能小于等于当前系统日期"),
	E_SIGN_ERROR_ENDDATE_LGE_STARTDATE_ERROR(2029,"协议失效日期不能小于等于协议生效日期"),
	E_SIGN_ERROR_USER_SIGNLOCATION_ERROR(2032,"用户签名域信息为空"),
	E_SIGN_ERROR_PARAM_BANKCARD_INFO_MULTIPLE_NOTSUPPORT(2034,"银行卡数量超限"),
	
	//业务异常
	//E_SIGN_ERROR_MERCHANT_NOT_EXISTS(3001,"商户未开通电子签章功能"),
	E_SIGN_ERROR_ACCOUNT_APPLY_NOT_CONSISTENCY_ERROR(3008,"证件信息不一致"),
	E_SIGN_ERROR_CERTIFICATE_TYPE_NOT_SUPPORT(3009,"证件类型目前只支持身份证"),
	E_SIGN_ERROR_USER_NOT_REGISTER_ERROR(3011,"用户信息未注册"),
	E_SIGN_ERROR_USER_CHANNEL_NOT_MATCH_ERROR(3012,"用户信息和渠道信息不匹配"),
	E_SIGN_ERROR_BATCH__NOT_EXIST_ERROR(3013,"批量信息不存在"),
	E_SIGN_ERROR_BATCH_BLANK_DETAIL(3014,"批量交易明细为空"),
	E_SIGN_ERROR_BATCH_EXCEED_MAX_COUNT(3015,"批量交易总笔数超限额"),
	E_SIGN_ERROR_BATCH_AMOUNT_NOT_EQUAR(3016,"批量交易总金额与明细汇总金额不一致"),
	E_SIGN_ERROR_BATCH_COUNT_NOT_EQUAR(3017,"批量交易总笔数与明细汇总笔数不一致"),
	E_SIGN_ERROR_MEDIA_OPERATOR_ERROR(3018,"文件操作处理异常"),
	E_SIGN_ERROR_BLACK_LIST_ERROR(3019,"黑名单用户系统拒绝服务"),
	E_SIGN_ERROR_ACCOUNT_REGISTER_PARAM_ERROR(3020,"此处为空，预留返回渠道异常内容"),
	E_SIGN_ERROR_ORDER_NO_NOT_EXISTS(3021,"订单编号不存在"),
	E_SIGN_ERROR_EFFECTIVE_CHECK_CODE_NOT_EXISTS(3022,"短信验证失败，请重新发送短信"),
	E_SIGN_ERROR_USER_NO_AUTH(3023,"用户未对此项目授权"),
	E_SIGN_ERROR_USER_HAD_AUTHED_SENDED(3024,"用户已授权，请不要重复发送验证码"),
	E_SIGN_ERROR_USER_HAD_AUTHED_CONFIRM(3025,"用户已授权，请不要重复确认验证码"),
	E_SIGN_ERROR_MERCHANT_STATUS_NOT_EFFECTIVE(3026,"商户状态不可用"),
	E_SIGN_ERROR_AUTH_CHANNEL_NOT_MATCH(3027,"授权渠道号与传入渠道不匹配"),
	E_SIGN_ERROR_SIGN_AVAILABLE_COUNT_NOT_ENOUGH(3028,"签约可用次数不足"),
	E_SIGN_ERROR_MODIFY_CONTRACT_STATUS_ERROR(3029,"修改合同状态失败"),
	E_SIGN_ERROR_ORDER_NOS_EXIST_ERROR(3030,"订单号重复，系统拒绝处理，重复订单号：{}"),
	E_SIGN_ERROR_PROJECTCODE_NOT_SAME_ERROR(3031,"项目编号与申请信息不一致"),
	E_SIGN_ERROR_USER_ID_NOT_SAME_ERROR(3032,"用户ID与申请信息不一致"),
	E_SIGN_ERROR_REMIND_AGAIN_ERROR(3033,"重复提醒"),
	E_SIGN_ERROR_ROLLBACK_AVAILABLE_COUTN_FAILED(3034,"回滚可用次数失败"),
	E_SIGN_ERROR_CONTRACT_COPY_EXCEPTION(3035,"合同文件复制出错"),
	E_SIGN_ERROR_SEND_CONTENT_IS_NULL(3036,"发送内容为空或者发送地址为空!"),
	E_SIGN_ERROR_MEDIA_UNZIP_ERROR(3050,"文件操作解压失败"), 
	E_SIGN_ERROR_PROJECT_CODE_ERROR(3051,"项目编号由商户编号加8位定长数字组成"),
	E_SIGN_ERROR_SN_NO_ERROR(3052,"流水号不能重复"),
	E_SIGN_ERROR_PARM_EMPTY_ERROR(3053,"userIds：注册用户ID列表不能为空"),
	E_SIGN_ERROR_SN_NO_EXIST_ERROR(3054,"流水号信息不存在"), 
	E_SIGN_ERROR_PARM_LENGTH_ERROR(3056,"userIds：注册用户ID列表长度不能超过100"), 
	E_SIGN_ERROR_PARM_MERCHANTID_ERROR(3057,"merchantId:商户编号最大长度为20位数字"),
	E_SIGN_ERROR_PARM_MERCHANTID_EMPTY_ERROR(3058,"merchantId:商户编号不能为空"),
	E_SIGN_ERROR_TEMPLATE_NO_REGISTER(3060,"模板未备案"), 
	E_SIGN_ERROR_CONTRACT_NAME_CONFLICT_EXCEPTION(3063,"同一天内上传的合同文件名称不能重复，请修改名称{}后再上传"),
	E_SIGN_ERROR_CONTRACT_CONFIRM_CLEARING_RETURN_NULL_EXCEPTION(3065,"确认电子合同验证码服务异常,渠道响应结果为空"),
	E_SIGN_ERROR_NETWORK_CONTRACT_UN_PREAUTH(3066,"预授权方未授权或者未授权成功"),
	E_SIGN_ERROR_NETWORK_CONTRACT_AGENCY_MERCHANT_ACCOUNT_NOT_EXISTS(3067,"代理商账户编号不存在"),
	E_SIGN_ERROR_USER_IS_OPENED(3068,"用户已开户，请勿重复提交"),
	E_SIGN_ERROR_MERCHANT_EXISTS(3069,"商户已开通电子签章功能，请勿重复提交"),
	E_SIGN_ERROR_CONTRACT_NOT_EXISTS(3079,"合同未签署"),
	E_SIGN_ERROR_CONTRACT_FRFUSED(3080,"合同已被拒绝"),
	E_SIGN_ERROR_CONTRACT_FILE_IS_IN_PROCESS(3081,"合同文件正在生成，请稍后"),
	E_SIGN_ERROR_CONTRACT_IS_IN_SIGN(3082,"合同正在签署"),
	
	MERCHANT_EXIST(3083,"商户号重复"),
	MERCHANT_NOT_EXIST(3084,"上级商户不存在"),
	FACE_RECOGNITION_ERROR_IMG_NOT_ENOUGH(4001, "图片数量不足"),
	
	SMS_AUTH_SUCCESS(4100,"验证通过"),
	SMS_AUTH_ERROR_NOT_CORRECT(4101,"验证码错误"),
	SMS_AUTH_ERROR_EXCEED_MAX_TIMES(4102,"验证超过最大次数"),
	SMS_AUTH_ERROR_EXCEED_VALID_TIME(4103,"验证码已过期"),
	SMS_AUTH_ERROR_HASE_VALID(4104,"验证码已经验证过"),
	SMS_AUTH_ERROR_ORDER_NO_NOT_EXIST(4105,"待验证记录不存在"),
	SMS_AUTH_ERROR_INVALID(4106,"验证码无效"),
	
	SIGN_CONFIG_NO_FIND(4107,"签约配置未找到"),
	
	SESAME_CREDIT_ERROR_NO_SCORE(4200,"未查询到芝麻分，请确认是否已经通过支付宝扫码并授权"),
	
	
	;

	TradeRetCodeEnum(int code, String message) {
		this.code = code;
		this.message = message;
	}

	private Integer code;

	private String message;

	public Integer getCode() {
		return code;
	}

	public void setCode(Integer code) {
		this.code = code;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

}
